language = "C"
include_version = true
includes = ["selene/core_types.h"]
no_includes = false
cpp_compat = true
after_includes = ""
############################ Code Style Options ################################
braces = "SameLine"
line_length = 100
tab_width = 2
documentation = true
documentation_style = "auto"
documentation_length = "full"
line_endings = "LF" # also "CR", "CRLF", "Native"
############################# Codegen Options ##################################
style = "both"
sort_by = "None"
usize_is_size_t = true

[export]
include = [
    "ErrorModelAPIVersion",
    "ErrorModelInstance",
    "ErrorModelSetResultInterface", 
    "ErrorModelSetResultInstance", 
    "SimulatorAPIVersion",
    "SimulatorInstance",
    "RuntimeAPIVersion",
    "RuntimeGetOperationInterface",
    "RuntimeGetOperationInstance",
    "RuntimeExtractOperationInterface",
    "RuntimeExtractOperationInstance",
    "Errno",
]
item_types = ["functions", "structs", "opaque", "enums", "typedefs"]
renaming_overrides_prefixing = false

[export.rename]
"ErrorModelAPIVersion" = "SeleneErrorModelAPIVersion"
"ErrorModelInstance" = "SeleneErrorModelInstance"
"ErrorModelSetResultInterface" = "SeleneErrorModelSetResultInterface" 
"ErrorModelSetResultInstance" = "SeleneErrorModelSetResultInstance" 
"SimulatorAPIVersion" = "SeleneSimulatorAPIVersion"
"SimulatorInstance" = "SeleneSimulatorInstance"
"RuntimeAPIVersion" = "SeleneRuntimeAPIVersion"
"RuntimeGetOperationInterface" = "SeleneRuntimeGetOperationInterface"
"RuntimeGetOperationInstance" = "SeleneRuntimeGetOperationInstance"
"RuntimeExtractOperationInterface" = "SeleneRuntimeExtractOperationInterface"
"RuntimeExtractOperationInstance" = "SeleneRuntimeExtractOperationInstance"
"Errno" = "SeleneErrno"

[export.mangle]
rename_types = "SnakeCase"

[fn]
rename_args = "None"
args = "vertical"

[enum]
rename_variants = "None"
add_sentinel = false
prefix_with_name = false
derive_helper_methods = false
derive_const_casts = false
derive_mut_casts = false
derive_tagged_enum_destructor = false
derive_tagged_enum_copy_constructor = false
enum_class = true
private_default_tagged_enum_constructor = false

[const]
allow_static_const = true
allow_constexpr = false
