name: release-please

on:
  push:
    branches:
      # temporary for CI testing
      - chore/release-separation

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: Create release PR
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@update-rp
        with:
          target-branch: ${{ github.ref_name }}
          token: ${{ secrets.HUGRBOT_PAT }}
