name: release-please

on:
  push:
    branches:
      # temporary for CI testing
      - chore/release-separation

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: Create release PR
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          config-file: .github/release-please/config.json
          manifest-file: .github/release-please/manifest.json
          target-branch: ${{ github.ref_name }}
